version: '3.3'

services:
  untrunc:
    build: ./untrunc
    container_name: untrunc
    volumes:
      - ./untrunc/app.py:/app.py
      - Jejaljejal:/data
    networks:
      - ssafy-net
    environment:
      - FLASK_DATA_PATH=/data/WebSocket
      - FLASK_FILE_PERIOD=15000
      - FLASK_FILE_DUPLICATE=0
    ports:
      - 8300:8300
    entrypoint: ["python3", "app.py"]

  backend:
      build: ./jejal
      container_name: jejal
      ports:
        - 8000:8000
      networks:
        - ssafy-net
      volumes:
      - Jejaljejal:/data
      entrypoint: ["java", "-jar", "/app.jar"] # entrypoint는 Dockerfile 설정을 사용합니다

volumes:
  Jejaljejal:
    external: false

networks:
  ssafy-net:
    external: false
