server:
  port: 8001
  servlet:
    context-path: "/api/"
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: JeJal
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jeju_accent?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    # 맥
    # password: soyoung
    # 윈도우
    password: soyoung95
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
    properties:
      hibernate.format_sql: false
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect



#logging
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: trace
    root: INFO
    org:
      springframework:
        web: INFO
        apache:
          tiles: DEBUG
        springframework:
          boot: DEBUG
  file:
    name: logs/json_file_upload.log
    pattern:
      file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"